#include <algorithm>

#include "TFile.h"
#include "TROOT.h"
#include "TH1F.h"
#include "TSystem.h"

#include "RooWorkspace.h"
#include "RooAbsData.h"

#include "RooStats/ModelConfig.h"
#include "RooStats/FeldmanCousins.h"
#include "RooStats/ToyMCSampler.h"
#include "RooStats/PointSetInterval.h"
#include "RooStats/ConfidenceBelt.h"

using namespace RooFit;
using namespace RooStats;

void runLimitFC_Raa3S_Workspace(const char *poiname="raa3", const char *pdfname="joint", const char *wsname="wcombo");


double CI = 0.95;

void runLimitFC_Raa3S_Workspace(const char *poiname, const char *pdfname, const char *wsname)
{
   RooRealVar *theVar; RooDataSet *data; RooAbsPdf *pdf;
   // Open input file with workspace (generated by rf14_wspacewrite)
   TFile *f = new TFile("TRIAL.root") ;

   // Retrieve workspace from file
   RooWorkspace* ws = (RooWorkspace*) f->Get(wsname);
   RooStats::ModelConfig *sbHypo = (RooStats::ModelConfig*) ws->obj("SbHypo");
   RooStats::ModelConfig *bHypo = (RooStats::ModelConfig*) ws->obj("BHypo");
   cout << "observables: " << sbHypo.GetObservables()->getSize() << endl;
   theVar = ws->var(poiname);
   // if (!theVar) theVar = ws->function(poiname);
   pdf = ws->pdf(pdfname);
   data =(RooDataSet *) ws->data("data");

   // Print structure of composite p.d.f.
   pdf->Print("t") ;


   // get a first estimate of where to look

   ProfileLikelihoodCalculator pl(*data,*pdf,*theVar);
   cout << data << " " << pdf << " " << theVar << endl;
   pl.SetConfidenceLevel(CI); 
   int ci = 100*CI;
   LikelihoodInterval* interval = pl.GetInterval();
   LikelihoodIntervalPlot plot(interval);
   TCanvas c4; c4.cd(); 
   plot.SetRange(0.,0.,0.05,3.);
   // plot.Draw();
   TLatex latexCI;
   latexCI.SetNDC();
   latexCI.SetTextSize(0.035);
   latexCI.DrawLatex(0.5,1.-0.05*2,Form("%s %d % C.I.",poiname,ci));
   latexCI.DrawLatex(0.5,1.-0.05*3,Form("Upper limit: %f",interval->UpperLimit(*theVar)));
   latexCI.DrawLatex(0.5,1.-0.05*4,Form("Lower limit: %f",interval->LowerLimit(*theVar)));
   TString intrvlName = theVar->GetTitle();
   // print out the iterval on the Parameter of Interest
   cout <<endl<< CI <<"\% interval on " <<theVar->GetName()<<" is : ["<<
      interval->LowerLimit(*theVar) << ", "<<
      interval->UpperLimit(*theVar) << "] "<<endl;
   pair<double, double> CnfdncIntrvl;
   CnfdncIntrvl.first  = interval->LowerLimit(*theVar);
   CnfdncIntrvl.second = interval->UpperLimit(*theVar);
   c4.SaveAs("ULtest.pdf");

   // now let's move to the hypo test inverter
   /////////////////////////////////////////////////////////////
   // Now get the POI for convenience
   // you may want to adjust the range of your POI
   ////////////////////////////////////////////////////////////
   RooRealVar* firstPOI = (RooRealVar*) sbHypo->GetParametersOfInterest()->first();
   double poimin = 0.5*max((double) 0.,CnfdncIntrvl.first);
   double poimax = 1.5*CnfdncIntrvl.second;
   cout << "Will scan between " << poimin << " and " << poimax << endl;
   firstPOI->setMin(poimin);
   firstPOI->setMax(poimax);

  /////////////////////////////////////////////
  // create and use the FeldmanCousins tool
  // to find and plot the 95% confidence interval
  // on the parameter of interest as specified
  // in the model config
  FeldmanCousins fc(*data,*sbHypo);
  fc.SetConfidenceLevel(CI); // 95% interval
  fc.AdditionalNToysFactor(0.5); // to speed up the result 
  fc.UseAdaptiveSampling(true); // speed it up a bit
  fc.SetNBins(10); // set how many points per parameter of interest to scan
  fc.CreateConfBelt(true); // save the information in the belt for plotting

  // Since this tool needs to throw toy MC the PDF needs to be
  // extended or the tool needs to know how many entries in a dataset
  // per pseudo experiment.  
  // In the 'number counting form' where the entries in the dataset
  // are counts, and not values of discriminating variables, the
  // datasets typically only have one entry and the PDF is not
  // extended.  
  if(!sbHypo->GetPdf()->canBeExtended()){
    if(data->numEntries()==1)     
      fc.FluctuateNumDataEntries(false);
    else
      cout <<"Not sure what to do about this model" <<endl;
  }

  // We can use PROOF to speed things along in parallel
   ProofConfig pc(*ws, 1, "workers=2", kFALSE);
   ToyMCSampler*  toymcsampler = (ToyMCSampler*) fc.GetTestStatSampler();
   toymcsampler->SetProofConfig(&pc);	// enable proof


  // Now get the interval
  PointSetInterval* intervalfc = fc.GetInterval();
  ConfidenceBelt* belt = fc.GetConfidenceBelt();
 
  // print out the iterval on the first Parameter of Interest
  RooRealVar* firstPOI = (RooRealVar*) sbHypo->GetParametersOfInterest()->first();
  cout << "\n95% interval on " <<firstPOI->GetName()<<" is : ["<<
    interval->LowerLimit(*firstPOI) << ", "<<
    interval->UpperLimit(*firstPOI) <<"] "<<endl;
}
