#include <algorithm>

void runStandardHypoTestInvDemo(const char *poiname="N_{#Upsilon(3S)}", const char *pdfname="pdf", const char *wsname="ws");

#include "StandardHypoTestInvDemo.C"

double CI = 0.95;

void runStandardHypoTestInvDemo(const char *poiname, const char *pdfname, const char *wsname)
{
   RooRealVar *theVar; RooDataSet *data; RooAbsPdf *pdf;
   // Open input file with workspace (generated by rf14_wspacewrite)
   TFile *f = new TFile("fitresult_combo.root") ;

   // Retrieve workspace from file
   RooWorkspace* ws = (RooWorkspace*) f->Get(wsname);
   theVar = ws->var(poiname);
   if (!theVar) theVar = ws->function(poiname);
   pdf = ws->pdf(pdfname);
   data =(RooDataSet *) ws->data("data");

   // Print structure of composite p.d.f.
   pdf->Print("t") ;


   // get a first estimate of where to look

   ProfileLikelihoodCalculator pl(*data,*pdf,*theVar);
   cout << data << " " << pdf << " " << theVar << endl;
   pl.SetConfidenceLevel(CI); 
   int ci = 100*CI;
   LikelihoodInterval* interval = pl.GetInterval();
   LikelihoodIntervalPlot plot(interval);
   TCanvas c4; c4.cd(); 
   plot.SetRange(50.,0.,250.,3.);
   // plot.Draw();
   TLatex latexCI;
   latexCI.SetNDC();
   latexCI.SetTextSize(0.035);
   latexCI.DrawLatex(0.5,1.-0.05*2,Form("%s %d % C.I.",poiname,ci));
   latexCI.DrawLatex(0.5,1.-0.05*3,Form("Upper limit: %f",interval->UpperLimit(*theVar)));
   latexCI.DrawLatex(0.5,1.-0.05*4,Form("Lower limit: %f",interval->LowerLimit(*theVar)));
   TString intrvlName = theVar->GetTitle();
   // print out the iterval on the Parameter of Interest
   cout <<endl<< CI <<"\% interval on " <<theVar->GetName()<<" is : ["<<
      interval->LowerLimit(*theVar) << ", "<<
      interval->UpperLimit(*theVar) << "] "<<endl;
   pair<double, double> CnfdncIntrvl;
   CnfdncIntrvl.first  = interval->LowerLimit(*theVar);
   CnfdncIntrvl.second = interval->UpperLimit(*theVar);
   c4.SaveAs("ULtest.pdf");

   // now let's move to the hypo test inverter
   ModelConfig modelConfig(ws);
   modelConfig.SetName("UpsilonModel");
   modelConfig.SetPdf(*pdf);
   RooArgSet paramOfInterest(*theVar);
   modelConfig.SetParametersOfInterest(paramOfInterest);
   RooRealVar *theObs;
   theObs = ws->var("invariantMass");
   RooArgSet observable(*theObs,ws->cat("dataCat"));
   modelConfig.SetObservables(observable);
   cout << "observables: " << modelConfig.GetObservables()->getSize() << endl;
   /////////////////////////////////////////////////////////////
   // Now get the POI for convenience
   // you may want to adjust the range of your POI
   ////////////////////////////////////////////////////////////
   RooRealVar* firstPOI = (RooRealVar*) modelConfig.GetParametersOfInterest()->first();
   double poimin = 0.5*max((double) 0.,CnfdncIntrvl.first);
   double poimax = 1.5*CnfdncIntrvl.second;
   cout << "Will scan between " << poimin << " and " << poimax << endl;
   firstPOI->setMin(poimin);
   firstPOI->setMax(poimax);

   // actually run the hypo test inverter

   // define calc type and test stat type
   // type = 0 Freq calculator 
   // type = 1 Hybrid calculator
   // type = 2 Asymptotic calculator  
   // type = 3 Asymptotic calculator using nominal Asimov data sets (not using fitted parameter values but nominal ones)
   //
   // testStatType = 0 LEP
   //              = 1 Tevatron 
   //              = 2 Profile Likelihood two sided
   //              = 3 Profile Likelihood one sided (i.e. = 0 if mu < mu_hat)
   //              = 4 Profile Likelihood signed ( pll = -pll if mu < mu_hat) 
   //              = 5 Max Likelihood Estimate as test statistic
   //              = 6 Number of observed event as test statistic
   //

   // 0,3,true for frequentist CLs; 2,3,true for asymptotic CLs; 0,2,false for FC
   int calculatorType = 0;
   int testStatType = 2;
   bool useCLs = false;
   // root> StandardHypoTestInvDemo("fileName","workspace name","S+B modelconfig name","B model name","data set name",calculator type, test statistic type, use CLS, 
   //                                number of points, xmin, xmax, number of toys, use number counting)
   StandardHypoTestInvDemo(f->GetName(),
         wsname,
         &modelConfig,
         0,
         "data",                 
         calculatorType,
         testStatType, 
         useCLs,  
         20,   
         poimin,  
         poimax, 
         1000,
         false,
         0);
}
